#!name=Spotify去广告
#!desc=移除播放广告，恢复歌手和专辑列表的正常展示。
#!author=001ProMax (https://github.com/001ProMax)
#!homepage=https://github.com/luestr/ProxyResource/blob/main/README.md
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/Spotify.png
#!version=2025.06.01
#!tag=去广告

[General]
# 开启 HTTPS 解密
mitm-hosts = *.spotify.com

[Script]
http-response ^https:\/\/.+\.spotify\.com(:443)?\/(?:bootstrap|user-customization-service) script-path=https://raw.githubusercontent.com/001ProMax/Surge/refs/heads/main/Script/Spotify.Crack.Dev.js, requires-body=true, binary-body-mode=true, timeout=3, argument=[true,true], tag=Spotify去广告

[Rewrite]
^https:\/\/.+\.spotify\.com\/pendragon\/ reject-dict
^https:\/\/(.+)\.spotify\.com(:443)?\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/(.*)platform=iphone header https://$1.spotify.com$2/$3/$4platform=ipad

[Rule]
AND,((DOMAIN-SUFFIX,spotify.com),(PROTOCOL,QUIC)),REJECT