#!name=Spotify(>=iOS15)
#!desc=部分解锁premium,音质不能设置为超高(建议登录后再打开脚本,重启app等待脚本生效)
#!author = ZEUS
# 功能: 1.去除播放广告 2.歌手/专辑列表正常展示 3.去除随机播放

[Header Rewrite]
# if-none-match返回304状态码
http-request ^https:\/\/spclient\.wg\.spotify\.com\/user-customization-service\/v1\/customize$ header-del if-none-match

[Script]
http-response ^https:\/\/.+\.spotify\.com(:443)?\/(?:bootstrap|user-customization-service) script-path=https://raw.githubusercontent.com/001ProMax/Surge/refs/heads/main/Script/Spotify.Crack.Dev.js, requires-body=true, binary-body-mode=true, timeout=3, argument=[true,true], tag=Spotify去广告