[Module]
name = Spotify去广告
description = 移除播放广告，恢复歌手和专辑列表的正常展示。
author = 001ProMax (https://github.com/001ProMax)
icon = https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/Spotify.png
version = 2025.06.01
homepage = https://github.com/luestr/ProxyResource/blob/main/README.md

[Arguments]
tab = true, 移除底栏创建按钮
useractivity = true, 启用Apple设备接力

[General]
mitm-hosts = *.spotify.com

[Rule]
DOMAIN-SUFFIX,spotify.com,REJECT
AND,DST-PORT,443,PROTOCOL,QUIC,REJECT

[Rewrite]
^https:\/\/.+\.spotify\.com\/pendragon\/ reject-dict
^https:\/\/(.+)\.spotify\.com(:443)?\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/(.*)platform=iphone header https://$1.spotify.com$2/$3/$4platform=ipad

[Script]
http-response ^https:\/\/.+\.spotify\.com(:443)?\/(?:bootstrap|user-customization-service) script-path=https://raw.githubusercontent.com/001ProMax/Surge/refs/heads/main/Script/Spotify.Crack.Dev.js, requires-body=true, binary-body-mode=true, timeout=3, argument=[{tab},{useractivity}], tag=Protobuf